"""Export and plotting of binding analysis results.

Writes the outcome of an analysis in forms that can be inspected without
re-running anything: an ``.xyz`` file per conformation (openable in any molecular
viewer, with the ligand included as an extra site), a JSON summary of the
energies and contacts, CSV sweep tables, and a small set of plots.

The plots deliberately show the exact ground state alongside the variational
result, because the interesting question is not only what energy the VQE reached
but whether it reached the right one.
"""

from __future__ import annotations

import json
from typing import TYPE_CHECKING, Any

import numpy as np

from constants import COORDINATES_COLUMN_WIDTH, DEFAULT_LIGAND_SYMBOL
from logger import get_logger

if TYPE_CHECKING:
    from pathlib import Path

    from analysis.ligand_analysis import BindingResult, SweepRecord, SystemOutcome
    from analysis.structure_decoder import DecodedStructure

logger = get_logger()


def write_structure_xyz(
    structure: DecodedStructure,
    sequence: str,
    filepath: Path,
    ligand_symbol: str = DEFAULT_LIGAND_SYMBOL,
) -> Path:
    """Write a decoded conformation to an ``.xyz`` file.

    The ligand, when present, is appended as one additional site so protein and
    ligand can be viewed together.

    Args:
        structure (DecodedStructure): Conformation to write.
        sequence (str): Residue symbols, one per backbone site.
        filepath (Path): Destination file.
        ligand_symbol (str, optional): Symbol to label the ligand with. Defaults
            to DEFAULT_LIGAND_SYMBOL.

    Returns:
        Path: The path written to.

    """
    filepath.parent.mkdir(parents=True, exist_ok=True)

    sites: list[tuple[str, np.ndarray]] = [
        (symbol, coordinate)
        for symbol, coordinate in zip(sequence, structure.coordinates, strict=True)
    ]
    if structure.ligand_position is not None:
        sites.append((ligand_symbol, structure.ligand_position))

    width: int = COORDINATES_COLUMN_WIDTH
    with filepath.open("w", encoding="utf-8") as handle:
        handle.write(f"{len(sites)}\n")
        handle.write("Generated by QFold-Thesis/quantum-protein-folding\n")
        for symbol, coordinate in sites:
            handle.write(
                f"{symbol:<2} {coordinate[0]:>{width}.4f} "
                f"{coordinate[1]:>{width}.4f} {coordinate[2]:>{width}.4f}\n"
            )

    logger.info("Wrote structure with %d sites to %s", len(sites), filepath)
    return filepath


def _outcome_to_dict(outcome: SystemOutcome) -> dict[str, Any]:
    """Summarise one solved system as plain data.

    Args:
        outcome (SystemOutcome): Result to summarise.

    Returns:
        dict[str, Any]: JSON-serialisable summary.

    """
    return {
        "label": outcome.label,
        "num_qubits": outcome.num_qubits,
        "exact_energy": outcome.exact.energy,
        "exact_bitstring": outcome.exact.bitstring,
        "exact_degeneracy": outcome.exact.degeneracy,
        "vqe_energy": outcome.vqe_energy,
        "vqe_error": outcome.vqe_error,
        "vqe_found_ground_state": outcome.vqe_found_ground_state,
        "turns": [turn.value for turn in outcome.structure.turns],
        "coordinates": outcome.structure.coordinates.tolist(),
        "ligand_position": (
            None
            if outcome.structure.ligand_position is None
            else outcome.structure.ligand_position.tolist()
        ),
        "claimed_contacts": outcome.structure.claimed_contacts,
        "realised_contacts": outcome.structure.realised_contacts,
        "squared_distances": outcome.structure.squared_distances,
        "vqe_convergence": outcome.vqe_energies,
    }


def write_binding_report(result: BindingResult, filepath: Path) -> Path:
    """Write a JSON summary of an apo/holo comparison.

    Args:
        result (BindingResult): Analysis result to serialise.
        filepath (Path): Destination file.

    Returns:
        Path: The path written to.

    """
    filepath.parent.mkdir(parents=True, exist_ok=True)

    payload: dict[str, Any] = {
        "sequence": result.sequence,
        "ligand": {
            "symbol": result.ligand.symbol,
            "num_steps": result.ligand.num_steps,
            "sublattice_parity": result.ligand.sublattice_parity,
            "eligible_residues": result.ligand.eligible_bead_indices(
                len(result.sequence)
            ),
        },
        "binding_energy": result.binding_energy,
        "bound_residues": result.bound_residues,
        "bound_symbols": result.bound_symbols(),
        "conformation_changed": result.conformation_changed,
        "apo": _outcome_to_dict(result.apo),
        "holo": _outcome_to_dict(result.holo),
    }

    with filepath.open("w", encoding="utf-8") as handle:
        json.dump(payload, handle, indent=2, ensure_ascii=False)

    logger.info("Wrote binding report to %s", filepath)
    return filepath


def plot_sweep(
    records: list[SweepRecord],
    parameter_key: str,
    filepath: Path,
    title: str,
    energy_key: str = "energy",
    conformation_key: str = "turns",
) -> Path:
    """Plot an energy sweep, marking where the conformation changes.

    Args:
        records (list[SweepRecord]): Sweep records.
        parameter_key (str): Key holding the swept parameter.
        filepath (Path): Destination image file.
        title (str): Plot title.
        energy_key (str, optional): Key holding the energy. Defaults to "energy".
        conformation_key (str, optional): Key holding the conformation
            fingerprint used to detect changes. Defaults to "turns".

    Returns:
        Path: The path written to.

    """
    import matplotlib  # noqa: PLC0415

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt  # noqa: PLC0415

    parameters: list[float] = [float(record[parameter_key]) for record in records]
    energies: list[float] = [float(record[energy_key]) for record in records]
    conformations: list[object] = [record[conformation_key] for record in records]

    figure, axes = plt.subplots(figsize=(8, 5))
    axes.plot(parameters, energies, marker="o", linewidth=1.6, color="#2b6cb0")

    for index in range(1, len(conformations)):
        if conformations[index] != conformations[index - 1]:
            boundary: float = (parameters[index] + parameters[index - 1]) / 2
            axes.axvline(
                boundary, color="#c53030", linestyle="--", linewidth=1.0, alpha=0.8
            )

    axes.set_xlabel(parameter_key.replace("_", " "))
    axes.set_ylabel("ground state energy")
    axes.set_title(title)
    axes.grid(visible=True, alpha=0.3)

    filepath.parent.mkdir(parents=True, exist_ok=True)
    figure.tight_layout()
    figure.savefig(filepath, dpi=150)
    plt.close(figure)

    logger.info("Wrote sweep plot to %s", filepath)
    return filepath


def plot_vqe_convergence(result: BindingResult, filepath: Path) -> Path:
    """Plot VQE convergence for both forms against their exact ground states.

    Args:
        result (BindingResult): Analysis result holding the convergence traces.
        filepath (Path): Destination image file.

    Returns:
        Path: The path written to.

    """
    import matplotlib  # noqa: PLC0415

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt  # noqa: PLC0415

    figure, axes = plt.subplots(figsize=(8, 5))

    for outcome, colour in ((result.apo, "#2b6cb0"), (result.holo, "#c53030")):
        if outcome.vqe_energies:
            axes.plot(
                range(1, len(outcome.vqe_energies) + 1),
                outcome.vqe_energies,
                label=f"{outcome.label} VQE",
                color=colour,
                linewidth=1.5,
            )
        axes.axhline(
            outcome.exact.energy,
            color=colour,
            linestyle=":",
            linewidth=1.2,
            label=f"{outcome.label} exact = {outcome.exact.energy:.4f}",
        )

    axes.set_xlabel("VQE evaluation")
    axes.set_ylabel("energy")
    axes.set_title(f"VQE convergence for {result.sequence}")
    axes.legend()
    axes.grid(visible=True, alpha=0.3)

    filepath.parent.mkdir(parents=True, exist_ok=True)
    figure.tight_layout()
    figure.savefig(filepath, dpi=150)
    plt.close(figure)

    logger.info("Wrote VQE convergence plot to %s", filepath)
    return filepath


def plot_binding_geometry(result: BindingResult, filepath: Path) -> Path:
    """Plot the apo and holo conformations side by side in 3D.

    Args:
        result (BindingResult): Analysis result holding both conformations.
        filepath (Path): Destination image file.

    Returns:
        Path: The path written to.

    """
    import matplotlib  # noqa: PLC0415

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt  # noqa: PLC0415

    figure = plt.figure(figsize=(11, 5))

    for position, outcome in enumerate((result.apo, result.holo), start=1):
        axes = figure.add_subplot(1, 2, position, projection="3d")
        coordinates = outcome.structure.coordinates

        axes.plot(
            coordinates[:, 0],
            coordinates[:, 1],
            coordinates[:, 2],
            color="#4a5568",
            linewidth=2.0,
        )
        for index, (symbol, coordinate) in enumerate(
            zip(result.sequence, coordinates, strict=True)
        ):
            x, y, z = (float(value) for value in coordinate)
            axes.scatter(x, y, z, s=90, color="#2b6cb0", depthshade=False)
            axes.text(x, y, z, f" {symbol}{index}", fontsize=8)

        if outcome.structure.ligand_position is not None:
            x, y, z = (float(value) for value in outcome.structure.ligand_position)
            axes.scatter(x, y, z, s=160, marker="*", color="#c53030", depthshade=False)
            axes.text(x, y, z, f" {result.ligand.symbol}", fontsize=9, color="#c53030")

        axes.set_title(f"{outcome.label}  E = {outcome.exact.energy:.4f}")
        axes.set_box_aspect((1, 1, 1))

    figure.suptitle(
        f"{result.sequence}   binding energy = {result.binding_energy:+.4f}"
    )
    filepath.parent.mkdir(parents=True, exist_ok=True)
    figure.tight_layout()
    figure.savefig(filepath, dpi=150)
    plt.close(figure)

    logger.info("Wrote binding geometry plot to %s", filepath)
    return filepath
